### ISSUE TITLE
About the code！

### ISSUE THREAD

**Issue by Lwy-1998** [MKashifAli/Motion_Blind_Video_Stabilization#1]
Hello!

I am really interest in your work, so when the code will be available?

**Comment by MKashifAli** [comment]
Hello!
Thank you for your interest in my work. Unfortunately, I have been quite busy with other things and haven't had time to clean the code but I will try to create a clean testing script and upload it by next weekend.

**Comment by Lwy-1998** [comment]
Thank you ! Your code will help me a lot! :)

**Comment by MKashifAli** [comment]
Hello! Sorry for the delay. I have uploaded minimal test scripts and a link to download model checkpoints for all stages. Please go over them and let me know if you have any further questions. 
Lastly, after the CVPR submission deadline, I might also have enough time to clean the training code but cannot say anything concrete.
Thanks.

**Comment by Lwy-1998** [comment]
Thanks for your kind sharing !  I will go over them soon!
BTW,  Is your new CVPR paper relate to video stabilization?

**Comment by Lwy-1998** [comment]
Oh I forgot your pretrained model have password. I did't find it

**Comment by MKashifAli** [comment]
> Thanks for your kind sharing ! I will go over them soon! BTW, Is your new CVPR paper relate to video stabilization?

You're welcome, It isn't related video stabilization but I am currently working on video stabilization as well.

**Comment by MKashifAli** [comment]
> Oh I forgot your pretrained model have password. I did't find it

Thank you for pointing it out, I have changed the link and removed the password, please let me know if you can download it now.

**Comment by Lwy-1998** [comment]
> 

Yes, thanks again!
