### ISSUE TITLE
About the training details.

### ISSUE THREAD

**Issue by Murray04** [MKashifAli/Motion_Blind_Video_Stabilization#2]
Thanks for your code! 
Will you provide the supplementary material? I'm interested in the training details.

**Comment by MKashifAli** [comment]
Hello! Sorry for the late reply. you can download the supplementary text from the BMVC website provided in README.md or directly from this [link](https://www.bmvc2021-virtualconference.com/assets/supp/0316_supp.zip). 
Hope this helps.

**Comment by Murray04** [comment]
Thanks a lot！
